// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExmapleClient is the client API for Exmaple service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExmapleClient interface {
	ServerReply(ctx context.Context, in *HellpRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type exmapleClient struct {
	cc grpc.ClientConnInterface
}

func NewExmapleClient(cc grpc.ClientConnInterface) ExmapleClient {
	return &exmapleClient{cc}
}

func (c *exmapleClient) ServerReply(ctx context.Context, in *HellpRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/hello.Exmaple/ServerReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExmapleServer is the server API for Exmaple service.
// All implementations must embed UnimplementedExmapleServer
// for forward compatibility
type ExmapleServer interface {
	ServerReply(context.Context, *HellpRequest) (*HelloResponse, error)
	mustEmbedUnimplementedExmapleServer()
}

// UnimplementedExmapleServer must be embedded to have forward compatible implementations.
type UnimplementedExmapleServer struct {
}

func (UnimplementedExmapleServer) ServerReply(context.Context, *HellpRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerReply not implemented")
}
func (UnimplementedExmapleServer) mustEmbedUnimplementedExmapleServer() {}

// UnsafeExmapleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExmapleServer will
// result in compilation errors.
type UnsafeExmapleServer interface {
	mustEmbedUnimplementedExmapleServer()
}

func RegisterExmapleServer(s grpc.ServiceRegistrar, srv ExmapleServer) {
	s.RegisterService(&Exmaple_ServiceDesc, srv)
}

func _Exmaple_ServerReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HellpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExmapleServer).ServerReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Exmaple/ServerReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExmapleServer).ServerReply(ctx, req.(*HellpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Exmaple_ServiceDesc is the grpc.ServiceDesc for Exmaple service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exmaple_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Exmaple",
	HandlerType: (*ExmapleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerReply",
			Handler:    _Exmaple_ServerReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
